---
name: scheduled
on:
  workflow_dispatch: { }  # Allows manually trigger this workflow
  schedule:
    - cron: "0 3 * * *"

permissions:
  pull-requests: write
  id-token: write
  contents: write

jobs:
  scheduled:
    uses: cloudposse/.github/.github/workflows/shared-terraform-scheduled.yml@289afbc41bbefd9a76f18024edc879e38145f1b4 # main
    secrets: inherit
